-- Generated by transform/generate_silver.py from data_dictionary.py and seeds/enum_mappings.csv.
-- Edit the generator, not this file.
{{ config(post_hook=export_parquet(partitioned=true)) }}

with raw as (
    select * from {{ bronze('call_center_interactions', partitioned=true) }}
),

manifest as (
    {{ bronze_manifest() }}
),

typed as (
    select
        {{ to_type('raw."interaction_id"', 'varchar') }} as "interaction_id",
        {{ to_type('raw."interaction_date"', 'timestamp') }} as "interaction_date",
        raw."interaction_date" as __raw_interaction_date,
        {{ to_type('raw."process_date"', 'date') }} as "process_date",
        raw."process_date" as __raw_process_date,
        {{ to_type('raw."customer_id"', 'varchar') }} as "customer_id",
        {{ to_type('raw."agent_id"', 'varchar') }} as "agent_id",
        {{ to_type('raw."interaction_type"', 'varchar') }} as "interaction_type",
        {{ to_type('raw."channel"', 'varchar') }} as "channel",
        {{ to_type('raw."contact_reason"', 'varchar') }} as "contact_reason",
        case raw."reason_category" when 'Transaccional' then 'Transactional' when 'Producto' then 'Product' when 'Técnico' then 'Technical' when 'Comercial' then 'Commercial' when 'Queja' then 'Complaint' when 'Retención' then 'Retention' else raw."reason_category" end as "reason_category",
        {{ to_type('raw."duration_seconds"', 'integer') }} as "duration_seconds",
        raw."duration_seconds" as __raw_duration_seconds,
        {{ to_type('raw."wait_time_seconds"', 'integer') }} as "wait_time_seconds",
        raw."wait_time_seconds" as __raw_wait_time_seconds,
        {{ to_type('raw."was_resolved"', 'boolean') }} as "was_resolved",
        raw."was_resolved" as __raw_was_resolved,
        {{ to_type('raw."requires_followup"', 'boolean') }} as "requires_followup",
        raw."requires_followup" as __raw_requires_followup,
        case raw."detected_sentiment" when 'Positivo' then 'Positive' when 'Negativo' then 'Negative' when 'Muy Negativo' then 'Very Negative' when 'Muy Positivo' then 'Very Positive' else raw."detected_sentiment" end as "detected_sentiment",
        {{ to_type('raw."sentiment_score"', 'decimal(3,2)') }} as "sentiment_score",
        raw."sentiment_score" as __raw_sentiment_score,
        {{ to_type('raw."customer_detected_accent"', 'varchar') }} as "customer_detected_accent",
        {{ to_type('raw."agent_used_accent"', 'varchar') }} as "agent_used_accent",
        {{ to_type('raw."was_escalated"', 'boolean') }} as "was_escalated",
        raw."was_escalated" as __raw_was_escalated,
        {{ to_type('raw."mentioned_products"', 'varchar') }} as "mentioned_products",
        {{ to_type('raw."has_transcript"', 'boolean') }} as "has_transcript",
        raw."has_transcript" as __raw_has_transcript,
        {{ to_type('raw."has_recording"', 'boolean') }} as "has_recording",
        raw."has_recording" as __raw_has_recording,
        regexp_extract(raw.filename, 'data/.*$') as _source_key,
        regexp_extract(raw.filename, 'year=(\d{4})', 1)::integer as year,
        regexp_extract(raw.filename, 'month=(\d{2})', 1)::integer as month
    from raw as raw
),

checked as (
    select
        *,
        list_filter([
            case when __raw_interaction_date is not null and "interaction_date" is null then 'cast_failed:interaction_date' end,
            case when __raw_process_date is not null and "process_date" is null then 'cast_failed:process_date' end,
            case when __raw_duration_seconds is not null and "duration_seconds" is null then 'cast_failed:duration_seconds' end,
            case when __raw_wait_time_seconds is not null and "wait_time_seconds" is null then 'cast_failed:wait_time_seconds' end,
            case when __raw_was_resolved is not null and "was_resolved" is null then 'cast_failed:was_resolved' end,
            case when __raw_requires_followup is not null and "requires_followup" is null then 'cast_failed:requires_followup' end,
            case when __raw_sentiment_score is not null and "sentiment_score" is null then 'cast_failed:sentiment_score' end,
            case when __raw_was_escalated is not null and "was_escalated" is null then 'cast_failed:was_escalated' end,
            case when __raw_has_transcript is not null and "has_transcript" is null then 'cast_failed:has_transcript' end,
            case when __raw_has_recording is not null and "has_recording" is null then 'cast_failed:has_recording' end,
            case when "interaction_id" is null then 'not_null:interaction_id' end,
            case when "interaction_date" is null then 'not_null:interaction_date' end,
            case when "process_date" is null then 'not_null:process_date' end,
            case when "customer_id" is null then 'not_null:customer_id' end,
            case when "interaction_type" is null then 'not_null:interaction_type' end,
            case when "channel" is null then 'not_null:channel' end,
            case when "contact_reason" is null then 'not_null:contact_reason' end,
            case when "reason_category" is null then 'not_null:reason_category' end,
            case when "requires_followup" is null then 'not_null:requires_followup' end,
            case when "was_escalated" is null then 'not_null:was_escalated' end,
            case when "has_transcript" is null then 'not_null:has_transcript' end,
            case when "has_recording" is null then 'not_null:has_recording' end,
            case when "interaction_type" not in ('Inbound Call', 'Outbound Call', 'Chat', 'Email', 'Video') then 'undocumented_value:interaction_type' end,
            case when "channel" not in ('Phone', 'Web Chat', 'WhatsApp', 'Email', 'App', 'Web') then 'undocumented_value:channel' end,
            case when "reason_category" not in ('Transactional', 'Product', 'Technical', 'Commercial', 'Complaint', 'Retention') then 'undocumented_value:reason_category' end,
            case when "detected_sentiment" not in ('Positive', 'Neutral', 'Negative', 'Very Negative', 'Very Positive') then 'undocumented_value:detected_sentiment' end,
            case when "sentiment_score" not between -1 and 1 then 'out_of_range:sentiment_score' end
        ], x -> x is not null) as _dq_issues
    from typed
)

select
    checked."interaction_id",
    checked."interaction_date",
    checked."process_date",
    checked."customer_id",
    checked."agent_id",
    checked."interaction_type",
    checked."channel",
    checked."contact_reason",
    checked."reason_category",
    checked."duration_seconds",
    checked."wait_time_seconds",
    checked."was_resolved",
    checked."requires_followup",
    checked."detected_sentiment",
    checked."sentiment_score",
    checked."customer_detected_accent",
    checked."agent_used_accent",
    checked."was_escalated",
    checked."mentioned_products",
    checked."has_transcript",
    checked."has_recording",
    checked.year,
    checked.month,
    checked._dq_issues,
    checked._source_key,
    manifest.ingested_at as _ingested_at,
    manifest.run_id as _run_id
from checked
left join manifest on manifest.source_key = checked._source_key
-- a PK delivered twice (late or corrected file): keep the most recent ingestion
qualify row_number() over (partition by checked."interaction_id" order by manifest.ingested_at desc nulls last, checked._source_key desc) = 1
