-- Generated by transform/generate_silver.py from data_dictionary.py and seeds/enum_mappings.csv.
-- Edit the generator, not this file.
{{ config(post_hook=export_parquet(partitioned=true)) }}

with raw as (
    select * from {{ bronze('campaign_sends', partitioned=true) }}
),

manifest as (
    {{ bronze_manifest() }}
),

typed as (
    select
        {{ to_type('raw."send_id"', 'varchar') }} as "send_id",
        {{ to_type('raw."send_date"', 'timestamp') }} as "send_date",
        raw."send_date" as __raw_send_date,
        {{ to_type('raw."process_date"', 'date') }} as "process_date",
        raw."process_date" as __raw_process_date,
        {{ to_type('raw."campaign_id"', 'varchar') }} as "campaign_id",
        {{ to_type('raw."customer_id"', 'varchar') }} as "customer_id",
        {{ to_type('raw."send_channel"', 'varchar') }} as "send_channel",
        {{ to_type('raw."template_used"', 'varchar') }} as "template_used",
        {{ to_type('raw."subject"', 'varchar') }} as "subject",
        {{ to_type('raw."send_status"', 'varchar') }} as "send_status",
        {{ to_type('raw."was_delivered"', 'boolean') }} as "was_delivered",
        raw."was_delivered" as __raw_was_delivered,
        {{ to_type('raw."was_opened"', 'boolean') }} as "was_opened",
        raw."was_opened" as __raw_was_opened,
        {{ to_type('raw."open_date"', 'timestamp') }} as "open_date",
        raw."open_date" as __raw_open_date,
        {{ to_type('raw."was_clicked"', 'boolean') }} as "was_clicked",
        raw."was_clicked" as __raw_was_clicked,
        {{ to_type('raw."click_date"', 'timestamp') }} as "click_date",
        raw."click_date" as __raw_click_date,
        {{ to_type('raw."click_count"', 'integer') }} as "click_count",
        raw."click_count" as __raw_click_count,
        {{ to_type('raw."had_conversion"', 'boolean') }} as "had_conversion",
        raw."had_conversion" as __raw_had_conversion,
        {{ to_type('raw."conversion_date"', 'timestamp') }} as "conversion_date",
        raw."conversion_date" as __raw_conversion_date,
        {{ to_type('raw."conversion_value"', 'decimal(15,2)') }} as "conversion_value",
        raw."conversion_value" as __raw_conversion_value,
        {{ to_type('raw."open_device"', 'varchar') }} as "open_device",
        case raw."open_country" when 'México' then 'Mexico' else raw."open_country" end as "open_country",
        {{ to_type('raw."failure_reason"', 'varchar') }} as "failure_reason",
        {{ to_type('raw."send_cost"', 'decimal(10,4)') }} as "send_cost",
        raw."send_cost" as __raw_send_cost,
        regexp_extract(raw.filename, 'data/.*$') as _source_key,
        regexp_extract(raw.filename, 'year=(\d{4})', 1)::integer as year,
        regexp_extract(raw.filename, 'month=(\d{2})', 1)::integer as month
    from raw as raw
),

checked as (
    select
        *,
        list_filter([
            case when __raw_send_date is not null and "send_date" is null then 'cast_failed:send_date' end,
            case when __raw_process_date is not null and "process_date" is null then 'cast_failed:process_date' end,
            case when __raw_was_delivered is not null and "was_delivered" is null then 'cast_failed:was_delivered' end,
            case when __raw_was_opened is not null and "was_opened" is null then 'cast_failed:was_opened' end,
            case when __raw_open_date is not null and "open_date" is null then 'cast_failed:open_date' end,
            case when __raw_was_clicked is not null and "was_clicked" is null then 'cast_failed:was_clicked' end,
            case when __raw_click_date is not null and "click_date" is null then 'cast_failed:click_date' end,
            case when __raw_click_count is not null and "click_count" is null then 'cast_failed:click_count' end,
            case when __raw_had_conversion is not null and "had_conversion" is null then 'cast_failed:had_conversion' end,
            case when __raw_conversion_date is not null and "conversion_date" is null then 'cast_failed:conversion_date' end,
            case when __raw_conversion_value is not null and "conversion_value" is null then 'cast_failed:conversion_value' end,
            case when __raw_send_cost is not null and "send_cost" is null then 'cast_failed:send_cost' end,
            case when "send_id" is null then 'not_null:send_id' end,
            case when "send_date" is null then 'not_null:send_date' end,
            case when "process_date" is null then 'not_null:process_date' end,
            case when "campaign_id" is null then 'not_null:campaign_id' end,
            case when "customer_id" is null then 'not_null:customer_id' end,
            case when "send_channel" is null then 'not_null:send_channel' end,
            case when "send_status" is null then 'not_null:send_status' end,
            case when "was_delivered" is null then 'not_null:was_delivered' end,
            case when "had_conversion" is null then 'not_null:had_conversion' end,
            case when "send_channel" not in ('Email', 'SMS', 'Push', 'WhatsApp', 'Voice') then 'undocumented_value:send_channel' end,
            case when "send_status" not in ('Sent', 'Failed', 'Bounced', 'Blocked') then 'undocumented_value:send_status' end
        ], x -> x is not null) as _dq_issues
    from typed
)

select
    checked."send_id",
    checked."send_date",
    checked."process_date",
    checked."campaign_id",
    checked."customer_id",
    checked."send_channel",
    checked."template_used",
    checked."subject",
    checked."send_status",
    checked."was_delivered",
    checked."was_opened",
    checked."open_date",
    checked."was_clicked",
    checked."click_date",
    checked."click_count",
    checked."had_conversion",
    checked."conversion_date",
    checked."conversion_value",
    checked."open_device",
    checked."open_country",
    checked."failure_reason",
    checked."send_cost",
    checked.year,
    checked.month,
    checked._dq_issues,
    checked._source_key,
    manifest.ingested_at as _ingested_at,
    manifest.run_id as _run_id
from checked
left join manifest on manifest.source_key = checked._source_key
-- a PK delivered twice (late or corrected file): keep the most recent ingestion
qualify row_number() over (partition by checked."send_id" order by manifest.ingested_at desc nulls last, checked._source_key desc) = 1
