-- Generated by transform/generate_silver.py from data_dictionary.py and seeds/enum_mappings.csv.
-- Edit the generator, not this file.
{{ config(post_hook=export_parquet(partitioned=false)) }}

with raw as (
    select * from {{ bronze('customers', partitioned=false) }}
),

manifest as (
    {{ bronze_manifest() }}
),

typed as (
    select
        {{ to_type('raw."customer_id"', 'varchar') }} as "customer_id",
        {{ to_type('raw."document_number"', 'varchar') }} as "document_number",
        case raw."document_type" when 'Pasaporte' then 'Passport' else raw."document_type" end as "document_type",
        {{ to_type('raw."first_name"', 'varchar') }} as "first_name",
        {{ to_type('raw."last_name"', 'varchar') }} as "last_name",
        {{ to_type('raw."date_of_birth"', 'date') }} as "date_of_birth",
        raw."date_of_birth" as __raw_date_of_birth,
        {{ to_type('raw."gender"', 'varchar') }} as "gender",
        {{ to_type('raw."email"', 'varchar') }} as "email",
        {{ to_type('raw."mobile_phone"', 'varchar') }} as "mobile_phone",
        {{ to_type('raw."landline_phone"', 'varchar') }} as "landline_phone",
        {{ to_type('raw."address"', 'varchar') }} as "address",
        {{ to_type('raw."city"', 'varchar') }} as "city",
        {{ to_type('raw."state"', 'varchar') }} as "state",
        case raw."country" when 'México' then 'Mexico' else raw."country" end as "country",
        {{ to_type('raw."postal_code"', 'varchar') }} as "postal_code",
        {{ to_type('raw."detected_accent"', 'varchar') }} as "detected_accent",
        {{ to_type('raw."segment"', 'varchar') }} as "segment",
        {{ to_type('raw."credit_score"', 'integer') }} as "credit_score",
        raw."credit_score" as __raw_credit_score,
        {{ to_type('raw."estimated_monthly_income"', 'decimal(12,2)') }} as "estimated_monthly_income",
        raw."estimated_monthly_income" as __raw_estimated_monthly_income,
        {{ to_type('raw."occupation"', 'varchar') }} as "occupation",
        {{ to_type('raw."marital_status"', 'varchar') }} as "marital_status",
        {{ to_type('raw."education_level"', 'varchar') }} as "education_level",
        {{ to_type('raw."registration_date"', 'timestamp') }} as "registration_date",
        raw."registration_date" as __raw_registration_date,
        {{ to_type('raw."registration_branch_id"', 'varchar') }} as "registration_branch_id",
        {{ to_type('raw."customer_status"', 'varchar') }} as "customer_status",
        {{ to_type('raw."last_updated"', 'timestamp') }} as "last_updated",
        raw."last_updated" as __raw_last_updated,
        {{ to_type('raw."accepts_marketing"', 'boolean') }} as "accepts_marketing",
        raw."accepts_marketing" as __raw_accepts_marketing,
        regexp_extract(raw.filename, 'data/.*$') as _source_key
    from raw as raw
),

checked as (
    select
        *,
        list_filter([
            case when __raw_date_of_birth is not null and "date_of_birth" is null then 'cast_failed:date_of_birth' end,
            case when __raw_credit_score is not null and "credit_score" is null then 'cast_failed:credit_score' end,
            case when __raw_estimated_monthly_income is not null and "estimated_monthly_income" is null then 'cast_failed:estimated_monthly_income' end,
            case when __raw_registration_date is not null and "registration_date" is null then 'cast_failed:registration_date' end,
            case when __raw_last_updated is not null and "last_updated" is null then 'cast_failed:last_updated' end,
            case when __raw_accepts_marketing is not null and "accepts_marketing" is null then 'cast_failed:accepts_marketing' end,
            case when "customer_id" is null then 'not_null:customer_id' end,
            case when "document_number" is null then 'not_null:document_number' end,
            case when "document_type" is null then 'not_null:document_type' end,
            case when "first_name" is null then 'not_null:first_name' end,
            case when "last_name" is null then 'not_null:last_name' end,
            case when "date_of_birth" is null then 'not_null:date_of_birth' end,
            case when "city" is null then 'not_null:city' end,
            case when "state" is null then 'not_null:state' end,
            case when "country" is null then 'not_null:country' end,
            case when "segment" is null then 'not_null:segment' end,
            case when "registration_date" is null then 'not_null:registration_date' end,
            case when "registration_branch_id" is null then 'not_null:registration_branch_id' end,
            case when "customer_status" is null then 'not_null:customer_status' end,
            case when "last_updated" is null then 'not_null:last_updated' end,
            case when "accepts_marketing" is null then 'not_null:accepts_marketing' end,
            case when "document_type" not in ('DNI', 'CURP', 'CC', 'CE', 'Passport') then 'undocumented_value:document_type' end,
            case when "gender" not in ('M', 'F', 'O') then 'undocumented_value:gender' end,
            case when "country" not in ('Mexico', 'Colombia', 'Argentina') then 'undocumented_value:country' end,
            case when "detected_accent" not in ('mexican', 'colombian', 'argentine', 'neutral') then 'undocumented_value:detected_accent' end,
            case when "segment" not in ('Premium', 'Plus', 'Basic', 'Student') then 'undocumented_value:segment' end,
            case when "customer_status" not in ('Active', 'Inactive', 'Suspended', 'Closed') then 'undocumented_value:customer_status' end,
            case when "credit_score" not between 300 and 850 then 'out_of_range:credit_score' end
        ], x -> x is not null) as _dq_issues
    from typed
)

select
    checked."customer_id",
    checked."document_number",
    checked."document_type",
    checked."first_name",
    checked."last_name",
    checked."date_of_birth",
    checked."gender",
    checked."email",
    checked."mobile_phone",
    checked."landline_phone",
    checked."address",
    checked."city",
    checked."state",
    checked."country",
    checked."postal_code",
    checked."detected_accent",
    checked."segment",
    checked."credit_score",
    checked."estimated_monthly_income",
    checked."occupation",
    checked."marital_status",
    checked."education_level",
    checked."registration_date",
    checked."registration_branch_id",
    checked."customer_status",
    checked."last_updated",
    checked."accepts_marketing",
    checked._dq_issues,
    checked._source_key,
    manifest.ingested_at as _ingested_at,
    manifest.run_id as _run_id
from checked
left join manifest on manifest.source_key = checked._source_key
-- a PK delivered twice (late or corrected file): keep the most recent ingestion
qualify row_number() over (partition by checked."customer_id" order by manifest.ingested_at desc nulls last, checked._source_key desc) = 1
