-- Generated by transform/generate_silver.py from data_dictionary.py and seeds/enum_mappings.csv.
-- Edit the generator, not this file.
{{ config(post_hook=export_parquet(partitioned=false)) }}

with raw as (
    select * from {{ bronze('products', partitioned=false) }}
),

manifest as (
    {{ bronze_manifest() }}
),

typed as (
    select
        {{ to_type('raw."product_id"', 'varchar') }} as "product_id",
        {{ to_type('raw."customer_id"', 'varchar') }} as "customer_id",
        case raw."product_type" when 'Cuenta Corriente' then 'Checking Account' when 'Cuenta Ahorro' then 'Savings Account' when 'Tarjeta Crédito' then 'Credit Card' when 'Tarjeta Débito' then 'Debit Card' when 'Préstamo Personal' then 'Personal Loan' when 'Préstamo Hipotecario' then 'Mortgage' when 'Inversión' then 'Investment' when 'Seguro' then 'Insurance' else raw."product_type" end as "product_type",
        {{ to_type('raw."product_number"', 'varchar') }} as "product_number",
        {{ to_type('raw."currency"', 'varchar') }} as "currency",
        {{ to_type('raw."current_balance"', 'decimal(15,2)') }} as "current_balance",
        raw."current_balance" as __raw_current_balance,
        {{ to_type('raw."credit_limit"', 'decimal(15,2)') }} as "credit_limit",
        raw."credit_limit" as __raw_credit_limit,
        {{ to_type('raw."interest_rate"', 'decimal(5,2)') }} as "interest_rate",
        raw."interest_rate" as __raw_interest_rate,
        {{ to_type('raw."opening_date"', 'date') }} as "opening_date",
        raw."opening_date" as __raw_opening_date,
        {{ to_type('raw."expiration_date"', 'date') }} as "expiration_date",
        raw."expiration_date" as __raw_expiration_date,
        {{ to_type('raw."opening_branch_id"', 'varchar') }} as "opening_branch_id",
        {{ to_type('raw."product_status"', 'varchar') }} as "product_status",
        {{ to_type('raw."opening_channel"', 'varchar') }} as "opening_channel",
        {{ to_type('raw."has_linked_app"', 'boolean') }} as "has_linked_app",
        raw."has_linked_app" as __raw_has_linked_app,
        {{ to_type('raw."days_past_due"', 'integer') }} as "days_past_due",
        raw."days_past_due" as __raw_days_past_due,
        {{ to_type('raw."last_transaction_date"', 'timestamp') }} as "last_transaction_date",
        raw."last_transaction_date" as __raw_last_transaction_date,
        {{ to_type('raw."last_updated"', 'timestamp') }} as "last_updated",
        raw."last_updated" as __raw_last_updated,
        regexp_extract(raw.filename, 'data/.*$') as _source_key
    from raw as raw
),

checked as (
    select
        *,
        list_filter([
            case when __raw_current_balance is not null and "current_balance" is null then 'cast_failed:current_balance' end,
            case when __raw_credit_limit is not null and "credit_limit" is null then 'cast_failed:credit_limit' end,
            case when __raw_interest_rate is not null and "interest_rate" is null then 'cast_failed:interest_rate' end,
            case when __raw_opening_date is not null and "opening_date" is null then 'cast_failed:opening_date' end,
            case when __raw_expiration_date is not null and "expiration_date" is null then 'cast_failed:expiration_date' end,
            case when __raw_has_linked_app is not null and "has_linked_app" is null then 'cast_failed:has_linked_app' end,
            case when __raw_days_past_due is not null and "days_past_due" is null then 'cast_failed:days_past_due' end,
            case when __raw_last_transaction_date is not null and "last_transaction_date" is null then 'cast_failed:last_transaction_date' end,
            case when __raw_last_updated is not null and "last_updated" is null then 'cast_failed:last_updated' end,
            case when "product_id" is null then 'not_null:product_id' end,
            case when "customer_id" is null then 'not_null:customer_id' end,
            case when "product_type" is null then 'not_null:product_type' end,
            case when "product_number" is null then 'not_null:product_number' end,
            case when "currency" is null then 'not_null:currency' end,
            case when "current_balance" is null then 'not_null:current_balance' end,
            case when "opening_date" is null then 'not_null:opening_date' end,
            case when "opening_branch_id" is null then 'not_null:opening_branch_id' end,
            case when "product_status" is null then 'not_null:product_status' end,
            case when "opening_channel" is null then 'not_null:opening_channel' end,
            case when "has_linked_app" is null then 'not_null:has_linked_app' end,
            case when "last_updated" is null then 'not_null:last_updated' end,
            case when "product_type" not in ('Checking Account', 'Savings Account', 'Credit Card', 'Debit Card', 'Personal Loan', 'Mortgage', 'Investment', 'Insurance') then 'undocumented_value:product_type' end,
            case when "currency" not in ('MXN', 'COP', 'ARS', 'USD') then 'undocumented_value:currency' end,
            case when "product_status" not in ('Active', 'Blocked', 'Closed', 'Suspended') then 'undocumented_value:product_status' end,
            case when "opening_channel" not in ('Branch', 'Web', 'App', 'Call Center') then 'undocumented_value:opening_channel' end
        ], x -> x is not null) as _dq_issues
    from typed
)

select
    checked."product_id",
    checked."customer_id",
    checked."product_type",
    checked."product_number",
    checked."currency",
    checked."current_balance",
    checked."credit_limit",
    checked."interest_rate",
    checked."opening_date",
    checked."expiration_date",
    checked."opening_branch_id",
    checked."product_status",
    checked."opening_channel",
    checked."has_linked_app",
    checked."days_past_due",
    checked."last_transaction_date",
    checked."last_updated",
    checked._dq_issues,
    checked._source_key,
    manifest.ingested_at as _ingested_at,
    manifest.run_id as _run_id
from checked
left join manifest on manifest.source_key = checked._source_key
-- a PK delivered twice (late or corrected file): keep the most recent ingestion
qualify row_number() over (partition by checked."product_id" order by manifest.ingested_at desc nulls last, checked._source_key desc) = 1
