-- Generated by transform/generate_silver.py from data_dictionary.py and seeds/enum_mappings.csv.
-- Edit the generator, not this file.
{{ config(post_hook=export_parquet(partitioned=true)) }}

with raw as (
    select * from {{ bronze('transactions', partitioned=true) }}
),

manifest as (
    {{ bronze_manifest() }}
),

typed as (
    select
        {{ to_type('raw."transaction_id"', 'varchar') }} as "transaction_id",
        {{ to_type('raw."transaction_date"', 'timestamp') }} as "transaction_date",
        raw."transaction_date" as __raw_transaction_date,
        {{ to_type('raw."process_date"', 'date') }} as "process_date",
        raw."process_date" as __raw_process_date,
        {{ to_type('raw."product_id"', 'varchar') }} as "product_id",
        {{ to_type('raw."customer_id"', 'varchar') }} as "customer_id",
        {{ to_type('raw."transaction_type"', 'varchar') }} as "transaction_type",
        {{ to_type('raw."transaction_category"', 'varchar') }} as "transaction_category",
        {{ to_type('raw."amount"', 'decimal(15,2)') }} as "amount",
        raw."amount" as __raw_amount,
        {{ to_type('raw."currency"', 'varchar') }} as "currency",
        {{ to_type('raw."amount_usd"', 'decimal(15,2)') }} as "amount_usd",
        raw."amount_usd" as __raw_amount_usd,
        {{ to_type('raw."channel"', 'varchar') }} as "channel",
        {{ to_type('raw."branch_id"', 'varchar') }} as "branch_id",
        {{ to_type('raw."merchant_name"', 'varchar') }} as "merchant_name",
        {{ to_type('raw."merchant_category"', 'varchar') }} as "merchant_category",
        case raw."transaction_country" when 'México' then 'Mexico' else raw."transaction_country" end as "transaction_country",
        {{ to_type('raw."transaction_city"', 'varchar') }} as "transaction_city",
        {{ to_type('raw."transaction_status"', 'varchar') }} as "transaction_status",
        {{ to_type('raw."response_code"', 'varchar') }} as "response_code",
        {{ to_type('raw."is_fraud"', 'boolean') }} as "is_fraud",
        raw."is_fraud" as __raw_is_fraud,
        {{ to_type('raw."fraud_score"', 'decimal(5,2)') }} as "fraud_score",
        raw."fraud_score" as __raw_fraud_score,
        {{ to_type('raw."latitude"', 'decimal(10,7)') }} as "latitude",
        raw."latitude" as __raw_latitude,
        {{ to_type('raw."longitude"', 'decimal(10,7)') }} as "longitude",
        raw."longitude" as __raw_longitude,
        regexp_extract(raw.filename, 'data/.*$') as _source_key,
        regexp_extract(raw.filename, 'year=(\d{4})', 1)::integer as year,
        regexp_extract(raw.filename, 'month=(\d{2})', 1)::integer as month
    from raw as raw
),

checked as (
    select
        *,
        list_filter([
            case when __raw_transaction_date is not null and "transaction_date" is null then 'cast_failed:transaction_date' end,
            case when __raw_process_date is not null and "process_date" is null then 'cast_failed:process_date' end,
            case when __raw_amount is not null and "amount" is null then 'cast_failed:amount' end,
            case when __raw_amount_usd is not null and "amount_usd" is null then 'cast_failed:amount_usd' end,
            case when __raw_is_fraud is not null and "is_fraud" is null then 'cast_failed:is_fraud' end,
            case when __raw_fraud_score is not null and "fraud_score" is null then 'cast_failed:fraud_score' end,
            case when __raw_latitude is not null and "latitude" is null then 'cast_failed:latitude' end,
            case when __raw_longitude is not null and "longitude" is null then 'cast_failed:longitude' end,
            case when "transaction_id" is null then 'not_null:transaction_id' end,
            case when "transaction_date" is null then 'not_null:transaction_date' end,
            case when "process_date" is null then 'not_null:process_date' end,
            case when "product_id" is null then 'not_null:product_id' end,
            case when "customer_id" is null then 'not_null:customer_id' end,
            case when "transaction_type" is null then 'not_null:transaction_type' end,
            case when "amount" is null then 'not_null:amount' end,
            case when "currency" is null then 'not_null:currency' end,
            case when "channel" is null then 'not_null:channel' end,
            case when "transaction_country" is null then 'not_null:transaction_country' end,
            case when "transaction_status" is null then 'not_null:transaction_status' end,
            case when "is_fraud" is null then 'not_null:is_fraud' end,
            case when "transaction_type" not in ('Deposit', 'Withdrawal', 'Transfer', 'Payment', 'Purchase', 'Adjustment') then 'undocumented_value:transaction_type' end,
            case when "transaction_category" not in ('Food', 'Transport', 'Services', 'Entertainment', 'Health', 'Other') then 'undocumented_value:transaction_category' end,
            case when "currency" not in ('MXN', 'COP', 'ARS', 'USD') then 'undocumented_value:currency' end,
            case when "channel" not in ('ATM', 'Branch', 'Web', 'App', 'POS', 'Transfer') then 'undocumented_value:channel' end,
            case when "transaction_status" not in ('Approved', 'Declined', 'Pending', 'Reversed') then 'undocumented_value:transaction_status' end,
            case when "fraud_score" not between 0 and 100 then 'out_of_range:fraud_score' end
        ], x -> x is not null) as _dq_issues
    from typed
)

select
    checked."transaction_id",
    checked."transaction_date",
    checked."process_date",
    checked."product_id",
    checked."customer_id",
    checked."transaction_type",
    checked."transaction_category",
    checked."amount",
    checked."currency",
    checked."amount_usd",
    checked."channel",
    checked."branch_id",
    checked."merchant_name",
    checked."merchant_category",
    checked."transaction_country",
    checked."transaction_city",
    checked."transaction_status",
    checked."response_code",
    checked."is_fraud",
    checked."fraud_score",
    checked."latitude",
    checked."longitude",
    checked.year,
    checked.month,
    checked._dq_issues,
    checked._source_key,
    manifest.ingested_at as _ingested_at,
    manifest.run_id as _run_id
from checked
left join manifest on manifest.source_key = checked._source_key
-- a PK delivered twice (late or corrected file): keep the most recent ingestion
qualify row_number() over (partition by checked."transaction_id" order by manifest.ingested_at desc nulls last, checked._source_key desc) = 1
