"""Generate the silver dbt models and their contracts/tests from data_dictionary.py.

The dictionary is the single source of truth: columns, types, PKs, NOT NULL, enums, ranges
and FKs. Enum value mappings (Spanish -> documented value) come from seeds/enum_mappings.csv.

Test policy:
  - error: what silver guarantees (PK unique/not null, every value cast to its documented type).
  - warn:  source conformity to the dictionary (NOT NULL, accepted values, FKs). These are
           source issues: silver keeps the rows and flags them in `_dq_issues` instead of failing.

Usage: uv run python pipeline/transform/generate_silver.py
"""

import csv
import sys
from collections import defaultdict
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
from data_dictionary import FOREIGN_KEYS, TABLES, TYPES  # noqa: E402

MODELS = HERE / "models" / "silver"
SKIP = {"digital_events"}  # ~15.6M rows; add when a workflow needs it


def q(value):
    return "'" + str(value).replace("'", "''") + "'"


def qi(name):
    """Quoted identifier (the dictionary has columns named `date` and `source`)."""
    return '"' + name + '"'


def load_mappings():
    maps = defaultdict(dict)
    with open(HERE / "seeds" / "enum_mappings.csv", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            maps[(r["table_name"], r["column_name"])][r["raw_value"]] = r["canonical_value"]
    return maps


def model_sql(table, spec, types, maps):
    partitioned = spec["kind"] == "fact"
    lines = [
        "-- Generated by transform/generate_silver.py from data_dictionary.py and seeds/enum_mappings.csv.",
        "-- Edit the generator, not this file.",
        f"{{{{ config(post_hook=export_parquet(partitioned={str(partitioned).lower()})) }}}}",
        "",
        "with raw as (",
        f"    select * from {{{{ bronze({q(table)}, partitioned={str(partitioned).lower()}) }}}}",
        "),",
        "",
        "manifest as (",
        "    {{ bronze_manifest() }}",
        "),",
        "",
        "typed as (",
        "    select",
    ]
    select = []
    for col, typ in types.items():
        src = f"raw.{qi(col)}"
        expr = f"{{{{ to_type({q(src)}, {q(typ)}) }}}}"
        mapping = maps.get((table, col))
        if mapping:
            whens = " ".join(f"when {q(k)} then {q(v)}" for k, v in mapping.items())
            expr = f"case {src} {whens} else {src} end"
        select.append(f"        {expr} as {qi(col)}")
        if typ != "varchar":
            select.append(f"        {src} as __raw_{col}")
    select.append("        regexp_extract(raw.filename, 'data/.*$') as _source_key")
    if partitioned:
        select.append("        regexp_extract(raw.filename, 'year=(\\d{4})', 1)::integer as year")
        select.append("        regexp_extract(raw.filename, 'month=(\\d{2})', 1)::integer as month")
    lines.append(",\n".join(select))
    lines += ["    from raw as raw", "),", "", "checked as (", "    select", "        *,", "        list_filter(["]

    checks = []
    for col, typ in types.items():
        if typ != "varchar":
            checks.append(f"case when __raw_{col} is not null and {qi(col)} is null then 'cast_failed:{col}' end")
    for col in spec["not_null"]:
        checks.append(f"case when {qi(col)} is null then 'not_null:{col}' end")
    for col, allowed in spec.get("enums", {}).items():
        values = ", ".join(q(v) for v in allowed)
        checks.append(f"case when {qi(col)} not in ({values}) then 'undocumented_value:{col}' end")
    for col, (lo, hi) in spec.get("ranges", {}).items():
        checks.append(f"case when {qi(col)} not between {lo} and {hi} then 'out_of_range:{col}' end")
    lines.append(",\n".join(f"            {c}" for c in checks))
    lines += ["        ], x -> x is not null) as _dq_issues", "    from typed", ")", "", "select"]

    out = [f"    checked.{qi(c)}" for c in types]
    if partitioned:
        out += ["    checked.year", "    checked.month"]
    out += ["    checked._dq_issues", "    checked._source_key",
            "    manifest.ingested_at as _ingested_at", "    manifest.run_id as _run_id"]
    lines.append(",\n".join(out))
    pk = ", ".join(f"checked.{qi(c)}" for c in spec["pk"])
    lines += [
        "from checked",
        "left join manifest on manifest.source_key = checked._source_key",
        "-- a PK delivered twice (late or corrected file): keep the most recent ingestion",
        f"qualify row_number() over (partition by {pk} order by manifest.ingested_at desc nulls last, "
        "checked._source_key desc) = 1",
        "",
    ]
    return "\n".join(lines)


def model_yml(table, spec, types):
    fks = {(child_col): (parent, pcol) for child, child_col, parent, pcol in FOREIGN_KEYS
           if child == table and parent not in SKIP}
    warn = {"config": {"severity": "warn"}}
    columns = []
    for col, typ in types.items():
        tests = []
        if spec["pk"] == [col]:
            tests += ["unique", "not_null"]
        elif col in spec["not_null"]:
            tests.append({"not_null": warn})
        if col in spec.get("unique", []):
            tests.append({"unique": warn})
        if col in spec.get("enums", {}):
            tests.append({"accepted_values": {"arguments": {"values": spec["enums"][col]}, **warn}})
        if col in fks:
            parent, pcol = fks[col]
            tests.append({"relationships": {"arguments": {"to": f"ref('{parent}')", "field": pcol}, **warn}})
        entry = {"name": col, "data_type": typ}
        if tests:
            entry["data_tests"] = tests
        columns.append(entry)
    if spec["kind"] == "fact":
        columns += [{"name": "year", "data_type": "integer", "description": "Partition year (from the bronze path)"},
                    {"name": "month", "data_type": "integer", "description": "Partition month (from the bronze path)"}]
    columns += [
        {"name": "_dq_issues", "data_type": "varchar[]",
         "description": "Data-quality issues of the row: "
                        "cast_failed / not_null / undocumented_value / out_of_range:<column>"},
        {"name": "_source_key", "data_type": "varchar", "description": "Bronze file the row came from"},
        {"name": "_ingested_at", "data_type": "timestamp", "description": "When that file was copied to bronze"},
        {"name": "_run_id", "data_type": "varchar", "description": "Bronze ingestion run"},
    ]
    model_tests = [{"no_dq_issue": {"arguments": {"prefix": "cast_failed"}}}]
    if len(spec["pk"]) > 1:
        model_tests.append({"unique_combination": {"arguments": {"columns": spec["pk"]}}})
    return {
        "name": table,
        "description": f"{table} ({spec['kind']}), typed and cleaned from bronze. "
                       f"Documented rows: {spec['rows']:,}. PK: {', '.join(spec['pk'])}.",
        "data_tests": model_tests,
        "columns": columns,
    }


def main():
    maps = load_mappings()
    MODELS.mkdir(parents=True, exist_ok=True)
    models = []
    for table, spec in TABLES.items():
        if table in SKIP:
            continue
        (MODELS / f"{table}.sql").write_text(model_sql(table, spec, TYPES[table], maps), encoding="utf-8")
        models.append(model_yml(table, spec, TYPES[table]))
    header = "# Generated by transform/generate_silver.py from data_dictionary.py. Edit the generator.\n"
    body = yaml.safe_dump({"version": 2, "models": models}, sort_keys=False, allow_unicode=True, width=120)
    (MODELS / "_silver.yml").write_text(header + body, encoding="utf-8")
    print(f"generated {len(models)} silver models in {MODELS.relative_to(HERE.parent)}")


if __name__ == "__main__":
    main()
