-- Generated by transform/generate_silver.py from data_dictionary.py and seeds/enum_mappings.csv.
-- Edit the generator, not this file.
{{ config(post_hook=export_parquet(partitioned=false)) }}

with raw as (
    select * from {{ bronze('branches', partitioned=false) }}
),

manifest as (
    {{ bronze_manifest() }}
),

typed as (
    select
        {{ to_type('raw."branch_id"', 'varchar') }} as "branch_id",
        {{ to_type('raw."branch_code"', 'varchar') }} as "branch_code",
        {{ to_type('raw."branch_name"', 'varchar') }} as "branch_name",
        {{ to_type('raw."branch_type"', 'varchar') }} as "branch_type",
        {{ to_type('raw."address"', 'varchar') }} as "address",
        {{ to_type('raw."city"', 'varchar') }} as "city",
        {{ to_type('raw."state"', 'varchar') }} as "state",
        case raw."country" when 'México' then 'Mexico' else raw."country" end as "country",
        {{ to_type('raw."postal_code"', 'varchar') }} as "postal_code",
        case raw."geographic_zone" when 'Urbana' then 'Urban' when 'Suburbana' then 'Suburban' else raw."geographic_zone" end as "geographic_zone",
        {{ to_type('raw."phone"', 'varchar') }} as "phone",
        {{ to_type('raw."email"', 'varchar') }} as "email",
        {{ to_type('raw."opening_time"', 'time') }} as "opening_time",
        raw."opening_time" as __raw_opening_time,
        {{ to_type('raw."closing_time"', 'time') }} as "closing_time",
        raw."closing_time" as __raw_closing_time,
        {{ to_type('raw."has_atms"', 'boolean') }} as "has_atms",
        raw."has_atms" as __raw_has_atms,
        {{ to_type('raw."atm_count"', 'integer') }} as "atm_count",
        raw."atm_count" as __raw_atm_count,
        {{ to_type('raw."has_teller_windows"', 'boolean') }} as "has_teller_windows",
        raw."has_teller_windows" as __raw_has_teller_windows,
        {{ to_type('raw."teller_window_count"', 'integer') }} as "teller_window_count",
        raw."teller_window_count" as __raw_teller_window_count,
        {{ to_type('raw."latitude"', 'decimal(10,7)') }} as "latitude",
        raw."latitude" as __raw_latitude,
        {{ to_type('raw."longitude"', 'decimal(10,7)') }} as "longitude",
        raw."longitude" as __raw_longitude,
        {{ to_type('raw."branch_opening_date"', 'date') }} as "branch_opening_date",
        raw."branch_opening_date" as __raw_branch_opening_date,
        {{ to_type('raw."branch_status"', 'varchar') }} as "branch_status",
        regexp_extract(raw.filename, 'data/.*$') as _source_key
    from raw as raw
),

checked as (
    select
        *,
        list_filter([
            case when __raw_opening_time is not null and "opening_time" is null then 'cast_failed:opening_time' end,
            case when __raw_closing_time is not null and "closing_time" is null then 'cast_failed:closing_time' end,
            case when __raw_has_atms is not null and "has_atms" is null then 'cast_failed:has_atms' end,
            case when __raw_atm_count is not null and "atm_count" is null then 'cast_failed:atm_count' end,
            case when __raw_has_teller_windows is not null and "has_teller_windows" is null then 'cast_failed:has_teller_windows' end,
            case when __raw_teller_window_count is not null and "teller_window_count" is null then 'cast_failed:teller_window_count' end,
            case when __raw_latitude is not null and "latitude" is null then 'cast_failed:latitude' end,
            case when __raw_longitude is not null and "longitude" is null then 'cast_failed:longitude' end,
            case when __raw_branch_opening_date is not null and "branch_opening_date" is null then 'cast_failed:branch_opening_date' end,
            case when "branch_id" is null then 'not_null:branch_id' end,
            case when "branch_code" is null then 'not_null:branch_code' end,
            case when "branch_name" is null then 'not_null:branch_name' end,
            case when "branch_type" is null then 'not_null:branch_type' end,
            case when "address" is null then 'not_null:address' end,
            case when "city" is null then 'not_null:city' end,
            case when "state" is null then 'not_null:state' end,
            case when "country" is null then 'not_null:country' end,
            case when "geographic_zone" is null then 'not_null:geographic_zone' end,
            case when "phone" is null then 'not_null:phone' end,
            case when "opening_time" is null then 'not_null:opening_time' end,
            case when "closing_time" is null then 'not_null:closing_time' end,
            case when "has_atms" is null then 'not_null:has_atms' end,
            case when "has_teller_windows" is null then 'not_null:has_teller_windows' end,
            case when "branch_opening_date" is null then 'not_null:branch_opening_date' end,
            case when "branch_status" is null then 'not_null:branch_status' end,
            case when "branch_type" not in ('Main', 'Express', 'Premium', 'Corporate') then 'undocumented_value:branch_type' end,
            case when "geographic_zone" not in ('Urban', 'Suburban', 'Rural') then 'undocumented_value:geographic_zone' end,
            case when "branch_status" not in ('Active', 'Temporarily Closed', 'Closed') then 'undocumented_value:branch_status' end
        ], x -> x is not null) as _dq_issues
    from typed
)

select
    checked."branch_id",
    checked."branch_code",
    checked."branch_name",
    checked."branch_type",
    checked."address",
    checked."city",
    checked."state",
    checked."country",
    checked."postal_code",
    checked."geographic_zone",
    checked."phone",
    checked."email",
    checked."opening_time",
    checked."closing_time",
    checked."has_atms",
    checked."atm_count",
    checked."has_teller_windows",
    checked."teller_window_count",
    checked."latitude",
    checked."longitude",
    checked."branch_opening_date",
    checked."branch_status",
    checked._dq_issues,
    checked._source_key,
    manifest.ingested_at as _ingested_at,
    manifest.run_id as _run_id
from checked
left join manifest on manifest.source_key = checked._source_key
-- a PK delivered twice (late or corrected file): keep the most recent ingestion
qualify row_number() over (partition by checked."branch_id" order by manifest.ingested_at desc nulls last, checked._source_key desc) = 1
