-- Generated by transform/generate_silver.py from data_dictionary.py and seeds/enum_mappings.csv.
-- Edit the generator, not this file.
{{ config(post_hook=export_parquet(partitioned=true)) }}

with raw as (
    select * from {{ bronze('call_transcripts', partitioned=true) }}
),

manifest as (
    {{ bronze_manifest() }}
),

typed as (
    select
        {{ to_type('raw."transcript_id"', 'varchar') }} as "transcript_id",
        {{ to_type('raw."interaction_id"', 'varchar') }} as "interaction_id",
        {{ to_type('raw."process_date"', 'date') }} as "process_date",
        raw."process_date" as __raw_process_date,
        {{ to_type('raw."customer_id"', 'varchar') }} as "customer_id",
        {{ to_type('raw."agent_id"', 'varchar') }} as "agent_id",
        {{ to_type('raw."full_text"', 'varchar') }} as "full_text",
        {{ to_type('raw."customer_text"', 'varchar') }} as "customer_text",
        {{ to_type('raw."agent_text"', 'varchar') }} as "agent_text",
        {{ to_type('raw."detected_language"', 'varchar') }} as "detected_language",
        {{ to_type('raw."detected_accent"', 'varchar') }} as "detected_accent",
        {{ to_type('raw."accent_confidence"', 'decimal(3,2)') }} as "accent_confidence",
        raw."accent_confidence" as __raw_accent_confidence,
        {{ to_type('raw."detected_keywords"', 'varchar') }} as "detected_keywords",
        {{ to_type('raw."mentioned_entities"', 'varchar') }} as "mentioned_entities",
        {{ to_type('raw."detected_intents"', 'varchar') }} as "detected_intents",
        {{ to_type('raw."main_topics"', 'varchar') }} as "main_topics",
        {{ to_type('raw."transcription_model"', 'varchar') }} as "transcription_model",
        {{ to_type('raw."audio_quality"', 'varchar') }} as "audio_quality",
        {{ to_type('raw."duration_seconds"', 'integer') }} as "duration_seconds",
        raw."duration_seconds" as __raw_duration_seconds,
        regexp_extract(raw.filename, 'data/.*$') as _source_key,
        regexp_extract(raw.filename, 'year=(\d{4})', 1)::integer as year,
        regexp_extract(raw.filename, 'month=(\d{2})', 1)::integer as month
    from raw as raw
),

checked as (
    select
        *,
        list_filter([
            case when __raw_process_date is not null and "process_date" is null then 'cast_failed:process_date' end,
            case when __raw_accent_confidence is not null and "accent_confidence" is null then 'cast_failed:accent_confidence' end,
            case when __raw_duration_seconds is not null and "duration_seconds" is null then 'cast_failed:duration_seconds' end,
            case when "transcript_id" is null then 'not_null:transcript_id' end,
            case when "interaction_id" is null then 'not_null:interaction_id' end,
            case when "process_date" is null then 'not_null:process_date' end,
            case when "customer_id" is null then 'not_null:customer_id' end,
            case when "agent_id" is null then 'not_null:agent_id' end,
            case when "full_text" is null then 'not_null:full_text' end,
            case when "detected_language" is null then 'not_null:detected_language' end,
            case when "transcription_model" is null then 'not_null:transcription_model' end,
            case when "duration_seconds" is null then 'not_null:duration_seconds' end,
            case when "audio_quality" not in ('High', 'Medium', 'Low') then 'undocumented_value:audio_quality' end,
            case when "accent_confidence" not between 0 and 1 then 'out_of_range:accent_confidence' end
        ], x -> x is not null) as _dq_issues
    from typed
)

select
    checked."transcript_id",
    checked."interaction_id",
    checked."process_date",
    checked."customer_id",
    checked."agent_id",
    checked."full_text",
    checked."customer_text",
    checked."agent_text",
    checked."detected_language",
    checked."detected_accent",
    checked."accent_confidence",
    checked."detected_keywords",
    checked."mentioned_entities",
    checked."detected_intents",
    checked."main_topics",
    checked."transcription_model",
    checked."audio_quality",
    checked."duration_seconds",
    checked.year,
    checked.month,
    checked._dq_issues,
    checked._source_key,
    manifest.ingested_at as _ingested_at,
    manifest.run_id as _run_id
from checked
left join manifest on manifest.source_key = checked._source_key
-- a PK delivered twice (late or corrected file): keep the most recent ingestion
qualify row_number() over (partition by checked."transcript_id" order by manifest.ingested_at desc nulls last, checked._source_key desc) = 1
