-- Generated by transform/generate_silver.py from data_dictionary.py and seeds/enum_mappings.csv.
-- Edit the generator, not this file.
{{ config(post_hook=export_parquet(partitioned=true)) }}

with raw as (
    select * from {{ bronze('complaints', partitioned=true) }}
),

manifest as (
    {{ bronze_manifest() }}
),

typed as (
    select
        {{ to_type('raw."complaint_id"', 'varchar') }} as "complaint_id",
        {{ to_type('raw."creation_date"', 'timestamp') }} as "creation_date",
        raw."creation_date" as __raw_creation_date,
        {{ to_type('raw."process_date"', 'date') }} as "process_date",
        raw."process_date" as __raw_process_date,
        {{ to_type('raw."customer_id"', 'varchar') }} as "customer_id",
        {{ to_type('raw."case_type"', 'varchar') }} as "case_type",
        {{ to_type('raw."category"', 'varchar') }} as "category",
        {{ to_type('raw."subcategory"', 'varchar') }} as "subcategory",
        {{ to_type('raw."reception_channel"', 'varchar') }} as "reception_channel",
        {{ to_type('raw."affected_product_id"', 'varchar') }} as "affected_product_id",
        {{ to_type('raw."related_branch_id"', 'varchar') }} as "related_branch_id",
        {{ to_type('raw."origin_interaction_id"', 'varchar') }} as "origin_interaction_id",
        {{ to_type('raw."description"', 'varchar') }} as "description",
        {{ to_type('raw."claimed_amount"', 'decimal(15,2)') }} as "claimed_amount",
        raw."claimed_amount" as __raw_claimed_amount,
        {{ to_type('raw."currency"', 'varchar') }} as "currency",
        {{ to_type('raw."priority"', 'varchar') }} as "priority",
        {{ to_type('raw."status"', 'varchar') }} as "status",
        {{ to_type('raw."assigned_agent_id"', 'varchar') }} as "assigned_agent_id",
        {{ to_type('raw."assignment_date"', 'timestamp') }} as "assignment_date",
        raw."assignment_date" as __raw_assignment_date,
        {{ to_type('raw."first_response_date"', 'timestamp') }} as "first_response_date",
        raw."first_response_date" as __raw_first_response_date,
        {{ to_type('raw."resolution_date"', 'timestamp') }} as "resolution_date",
        raw."resolution_date" as __raw_resolution_date,
        {{ to_type('raw."closing_date"', 'timestamp') }} as "closing_date",
        raw."closing_date" as __raw_closing_date,
        {{ to_type('raw."sla_breached"', 'boolean') }} as "sla_breached",
        raw."sla_breached" as __raw_sla_breached,
        {{ to_type('raw."resolution_days"', 'integer') }} as "resolution_days",
        raw."resolution_days" as __raw_resolution_days,
        {{ to_type('raw."resolution"', 'varchar') }} as "resolution",
        {{ to_type('raw."compensation_granted"', 'decimal(15,2)') }} as "compensation_granted",
        raw."compensation_granted" as __raw_compensation_granted,
        {{ to_type('raw."resolution_satisfaction"', 'integer') }} as "resolution_satisfaction",
        raw."resolution_satisfaction" as __raw_resolution_satisfaction,
        {{ to_type('raw."is_repeat_complainer"', 'boolean') }} as "is_repeat_complainer",
        raw."is_repeat_complainer" as __raw_is_repeat_complainer,
        regexp_extract(raw.filename, 'data/.*$') as _source_key,
        regexp_extract(raw.filename, 'year=(\d{4})', 1)::integer as year,
        regexp_extract(raw.filename, 'month=(\d{2})', 1)::integer as month
    from raw as raw
),

checked as (
    select
        *,
        list_filter([
            case when __raw_creation_date is not null and "creation_date" is null then 'cast_failed:creation_date' end,
            case when __raw_process_date is not null and "process_date" is null then 'cast_failed:process_date' end,
            case when __raw_claimed_amount is not null and "claimed_amount" is null then 'cast_failed:claimed_amount' end,
            case when __raw_assignment_date is not null and "assignment_date" is null then 'cast_failed:assignment_date' end,
            case when __raw_first_response_date is not null and "first_response_date" is null then 'cast_failed:first_response_date' end,
            case when __raw_resolution_date is not null and "resolution_date" is null then 'cast_failed:resolution_date' end,
            case when __raw_closing_date is not null and "closing_date" is null then 'cast_failed:closing_date' end,
            case when __raw_sla_breached is not null and "sla_breached" is null then 'cast_failed:sla_breached' end,
            case when __raw_resolution_days is not null and "resolution_days" is null then 'cast_failed:resolution_days' end,
            case when __raw_compensation_granted is not null and "compensation_granted" is null then 'cast_failed:compensation_granted' end,
            case when __raw_resolution_satisfaction is not null and "resolution_satisfaction" is null then 'cast_failed:resolution_satisfaction' end,
            case when __raw_is_repeat_complainer is not null and "is_repeat_complainer" is null then 'cast_failed:is_repeat_complainer' end,
            case when "complaint_id" is null then 'not_null:complaint_id' end,
            case when "creation_date" is null then 'not_null:creation_date' end,
            case when "process_date" is null then 'not_null:process_date' end,
            case when "customer_id" is null then 'not_null:customer_id' end,
            case when "case_type" is null then 'not_null:case_type' end,
            case when "category" is null then 'not_null:category' end,
            case when "reception_channel" is null then 'not_null:reception_channel' end,
            case when "description" is null then 'not_null:description' end,
            case when "priority" is null then 'not_null:priority' end,
            case when "status" is null then 'not_null:status' end,
            case when "sla_breached" is null then 'not_null:sla_breached' end,
            case when "is_repeat_complainer" is null then 'not_null:is_repeat_complainer' end,
            case when "case_type" not in ('Complaint', 'Claim', 'Request', 'Suggestion') then 'undocumented_value:case_type' end,
            case when "reception_channel" not in ('Call Center', 'Email', 'Web', 'App', 'Branch', 'Regulator') then 'undocumented_value:reception_channel' end,
            case when "priority" not in ('Low', 'Medium', 'High', 'Critical') then 'undocumented_value:priority' end,
            case when "status" not in ('Open', 'In Process', 'Escalated', 'Resolved', 'Closed', 'Rejected') then 'undocumented_value:status' end,
            case when "resolution_satisfaction" not between 1 and 5 then 'out_of_range:resolution_satisfaction' end
        ], x -> x is not null) as _dq_issues
    from typed
)

select
    checked."complaint_id",
    checked."creation_date",
    checked."process_date",
    checked."customer_id",
    checked."case_type",
    checked."category",
    checked."subcategory",
    checked."reception_channel",
    checked."affected_product_id",
    checked."related_branch_id",
    checked."origin_interaction_id",
    checked."description",
    checked."claimed_amount",
    checked."currency",
    checked."priority",
    checked."status",
    checked."assigned_agent_id",
    checked."assignment_date",
    checked."first_response_date",
    checked."resolution_date",
    checked."closing_date",
    checked."sla_breached",
    checked."resolution_days",
    checked."resolution",
    checked."compensation_granted",
    checked."resolution_satisfaction",
    checked."is_repeat_complainer",
    checked.year,
    checked.month,
    checked._dq_issues,
    checked._source_key,
    manifest.ingested_at as _ingested_at,
    manifest.run_id as _run_id
from checked
left join manifest on manifest.source_key = checked._source_key
-- a PK delivered twice (late or corrected file): keep the most recent ingestion
qualify row_number() over (partition by checked."complaint_id" order by manifest.ingested_at desc nulls last, checked._source_key desc) = 1
