-- Generated by transform/generate_silver.py from data_dictionary.py and seeds/enum_mappings.csv.
-- Edit the generator, not this file.
{{ config(post_hook=export_parquet(partitioned=false)) }}

with raw as (
    select * from {{ bronze('daily_exchange_rates', partitioned=false) }}
),

manifest as (
    {{ bronze_manifest() }}
),

typed as (
    select
        {{ to_type('raw."date"', 'date') }} as "date",
        raw."date" as __raw_date,
        {{ to_type('raw."source_currency"', 'varchar') }} as "source_currency",
        {{ to_type('raw."target_currency"', 'varchar') }} as "target_currency",
        {{ to_type('raw."exchange_rate"', 'decimal(12,6)') }} as "exchange_rate",
        raw."exchange_rate" as __raw_exchange_rate,
        {{ to_type('raw."buy_rate"', 'decimal(12,6)') }} as "buy_rate",
        raw."buy_rate" as __raw_buy_rate,
        {{ to_type('raw."sell_rate"', 'decimal(12,6)') }} as "sell_rate",
        raw."sell_rate" as __raw_sell_rate,
        {{ to_type('raw."source"', 'varchar') }} as "source",
        regexp_extract(raw.filename, 'data/.*$') as _source_key
    from raw as raw
),

checked as (
    select
        *,
        list_filter([
            case when __raw_date is not null and "date" is null then 'cast_failed:date' end,
            case when __raw_exchange_rate is not null and "exchange_rate" is null then 'cast_failed:exchange_rate' end,
            case when __raw_buy_rate is not null and "buy_rate" is null then 'cast_failed:buy_rate' end,
            case when __raw_sell_rate is not null and "sell_rate" is null then 'cast_failed:sell_rate' end,
            case when "date" is null then 'not_null:date' end,
            case when "source_currency" is null then 'not_null:source_currency' end,
            case when "target_currency" is null then 'not_null:target_currency' end,
            case when "exchange_rate" is null then 'not_null:exchange_rate' end,
            case when "source_currency" not in ('MXN', 'COP', 'ARS', 'USD') then 'undocumented_value:source_currency' end,
            case when "target_currency" not in ('MXN', 'COP', 'ARS', 'USD') then 'undocumented_value:target_currency' end
        ], x -> x is not null) as _dq_issues
    from typed
)

select
    checked."date",
    checked."source_currency",
    checked."target_currency",
    checked."exchange_rate",
    checked."buy_rate",
    checked."sell_rate",
    checked."source",
    checked._dq_issues,
    checked._source_key,
    manifest.ingested_at as _ingested_at,
    manifest.run_id as _run_id
from checked
left join manifest on manifest.source_key = checked._source_key
-- a PK delivered twice (late or corrected file): keep the most recent ingestion
qualify row_number() over (partition by checked."date", checked."source_currency", checked."target_currency" order by manifest.ingested_at desc nulls last, checked._source_key desc) = 1
