-- Generated by transform/generate_silver.py from data_dictionary.py and seeds/enum_mappings.csv.
-- Edit the generator, not this file.
{{ config(post_hook=export_parquet(partitioned=false)) }}

with raw as (
    select * from {{ bronze('marketing_campaigns', partitioned=false) }}
),

manifest as (
    {{ bronze_manifest() }}
),

typed as (
    select
        {{ to_type('raw."campaign_id"', 'varchar') }} as "campaign_id",
        {{ to_type('raw."campaign_name"', 'varchar') }} as "campaign_name",
        {{ to_type('raw."description"', 'varchar') }} as "description",
        {{ to_type('raw."campaign_type"', 'varchar') }} as "campaign_type",
        {{ to_type('raw."campaign_objective"', 'varchar') }} as "campaign_objective",
        {{ to_type('raw."promoted_product"', 'varchar') }} as "promoted_product",
        {{ to_type('raw."target_segment"', 'varchar') }} as "target_segment",
        {{ to_type('raw."target_country"', 'varchar') }} as "target_country",
        {{ to_type('raw."start_date"', 'date') }} as "start_date",
        raw."start_date" as __raw_start_date,
        {{ to_type('raw."end_date"', 'date') }} as "end_date",
        raw."end_date" as __raw_end_date,
        {{ to_type('raw."budget"', 'decimal(12,2)') }} as "budget",
        raw."budget" as __raw_budget,
        {{ to_type('raw."campaign_status"', 'varchar') }} as "campaign_status",
        {{ to_type('raw."expected_conversion_rate"', 'decimal(5,2)') }} as "expected_conversion_rate",
        raw."expected_conversion_rate" as __raw_expected_conversion_rate,
        regexp_extract(raw.filename, 'data/.*$') as _source_key
    from raw as raw
),

checked as (
    select
        *,
        list_filter([
            case when __raw_start_date is not null and "start_date" is null then 'cast_failed:start_date' end,
            case when __raw_end_date is not null and "end_date" is null then 'cast_failed:end_date' end,
            case when __raw_budget is not null and "budget" is null then 'cast_failed:budget' end,
            case when __raw_expected_conversion_rate is not null and "expected_conversion_rate" is null then 'cast_failed:expected_conversion_rate' end,
            case when "campaign_id" is null then 'not_null:campaign_id' end,
            case when "campaign_name" is null then 'not_null:campaign_name' end,
            case when "campaign_type" is null then 'not_null:campaign_type' end,
            case when "campaign_objective" is null then 'not_null:campaign_objective' end,
            case when "start_date" is null then 'not_null:start_date' end,
            case when "end_date" is null then 'not_null:end_date' end,
            case when "campaign_status" is null then 'not_null:campaign_status' end,
            case when "campaign_type" not in ('Email', 'SMS', 'Push', 'WhatsApp', 'Voice', 'Mix') then 'undocumented_value:campaign_type' end,
            case when "campaign_objective" not in ('Acquisition', 'Retention', 'Cross-sell', 'Up-sell', 'Reactivation') then 'undocumented_value:campaign_objective' end,
            case when "campaign_status" not in ('Planned', 'Active', 'Paused', 'Completed') then 'undocumented_value:campaign_status' end
        ], x -> x is not null) as _dq_issues
    from typed
)

select
    checked."campaign_id",
    checked."campaign_name",
    checked."description",
    checked."campaign_type",
    checked."campaign_objective",
    checked."promoted_product",
    checked."target_segment",
    checked."target_country",
    checked."start_date",
    checked."end_date",
    checked."budget",
    checked."campaign_status",
    checked."expected_conversion_rate",
    checked._dq_issues,
    checked._source_key,
    manifest.ingested_at as _ingested_at,
    manifest.run_id as _run_id
from checked
left join manifest on manifest.source_key = checked._source_key
-- a PK delivered twice (late or corrected file): keep the most recent ingestion
qualify row_number() over (partition by checked."campaign_id" order by manifest.ingested_at desc nulls last, checked._source_key desc) = 1
