-- Generated by transform/generate_silver.py from data_dictionary.py and seeds/enum_mappings.csv.
-- Edit the generator, not this file.
{{ config(post_hook=export_parquet(partitioned=true)) }}

with raw as (
    select * from {{ bronze('satisfaction_surveys', partitioned=true) }}
),

manifest as (
    {{ bronze_manifest() }}
),

typed as (
    select
        {{ to_type('raw."survey_id"', 'varchar') }} as "survey_id",
        {{ to_type('raw."survey_date"', 'timestamp') }} as "survey_date",
        raw."survey_date" as __raw_survey_date,
        {{ to_type('raw."process_date"', 'date') }} as "process_date",
        raw."process_date" as __raw_process_date,
        {{ to_type('raw."interaction_id"', 'varchar') }} as "interaction_id",
        {{ to_type('raw."customer_id"', 'varchar') }} as "customer_id",
        {{ to_type('raw."agent_id"', 'varchar') }} as "agent_id",
        {{ to_type('raw."survey_type"', 'varchar') }} as "survey_type",
        {{ to_type('raw."send_channel"', 'varchar') }} as "send_channel",
        {{ to_type('raw."main_score"', 'integer') }} as "main_score",
        raw."main_score" as __raw_main_score,
        {{ to_type('raw."nps_category"', 'varchar') }} as "nps_category",
        {{ to_type('raw."question_1_text"', 'varchar') }} as "question_1_text",
        {{ to_type('raw."question_1_response"', 'integer') }} as "question_1_response",
        raw."question_1_response" as __raw_question_1_response,
        {{ to_type('raw."question_2_text"', 'varchar') }} as "question_2_text",
        {{ to_type('raw."question_2_response"', 'integer') }} as "question_2_response",
        raw."question_2_response" as __raw_question_2_response,
        {{ to_type('raw."question_3_text"', 'varchar') }} as "question_3_text",
        {{ to_type('raw."question_3_response"', 'integer') }} as "question_3_response",
        raw."question_3_response" as __raw_question_3_response,
        {{ to_type('raw."open_comments"', 'varchar') }} as "open_comments",
        {{ to_type('raw."comment_sentiment"', 'varchar') }} as "comment_sentiment",
        {{ to_type('raw."response_time_hours"', 'decimal(8,2)') }} as "response_time_hours",
        raw."response_time_hours" as __raw_response_time_hours,
        {{ to_type('raw."campaign_response_rate"', 'decimal(5,2)') }} as "campaign_response_rate",
        raw."campaign_response_rate" as __raw_campaign_response_rate,
        regexp_extract(raw.filename, 'data/.*$') as _source_key,
        regexp_extract(raw.filename, 'year=(\d{4})', 1)::integer as year,
        regexp_extract(raw.filename, 'month=(\d{2})', 1)::integer as month
    from raw as raw
),

checked as (
    select
        *,
        list_filter([
            case when __raw_survey_date is not null and "survey_date" is null then 'cast_failed:survey_date' end,
            case when __raw_process_date is not null and "process_date" is null then 'cast_failed:process_date' end,
            case when __raw_main_score is not null and "main_score" is null then 'cast_failed:main_score' end,
            case when __raw_question_1_response is not null and "question_1_response" is null then 'cast_failed:question_1_response' end,
            case when __raw_question_2_response is not null and "question_2_response" is null then 'cast_failed:question_2_response' end,
            case when __raw_question_3_response is not null and "question_3_response" is null then 'cast_failed:question_3_response' end,
            case when __raw_response_time_hours is not null and "response_time_hours" is null then 'cast_failed:response_time_hours' end,
            case when __raw_campaign_response_rate is not null and "campaign_response_rate" is null then 'cast_failed:campaign_response_rate' end,
            case when "survey_id" is null then 'not_null:survey_id' end,
            case when "survey_date" is null then 'not_null:survey_date' end,
            case when "process_date" is null then 'not_null:process_date' end,
            case when "customer_id" is null then 'not_null:customer_id' end,
            case when "survey_type" is null then 'not_null:survey_type' end,
            case when "send_channel" is null then 'not_null:send_channel' end,
            case when "main_score" is null then 'not_null:main_score' end,
            case when "survey_type" not in ('CSAT', 'NPS', 'CES') then 'undocumented_value:survey_type' end,
            case when "send_channel" not in ('Email', 'SMS', 'IVR', 'App', 'Web') then 'undocumented_value:send_channel' end,
            case when "nps_category" not in ('Promoter', 'Passive', 'Detractor') then 'undocumented_value:nps_category' end,
            case when "main_score" not between 0 and 10 then 'out_of_range:main_score' end,
            case when "question_1_response" not between 1 and 5 then 'out_of_range:question_1_response' end,
            case when "question_2_response" not between 1 and 5 then 'out_of_range:question_2_response' end,
            case when "question_3_response" not between 1 and 5 then 'out_of_range:question_3_response' end
        ], x -> x is not null) as _dq_issues
    from typed
)

select
    checked."survey_id",
    checked."survey_date",
    checked."process_date",
    checked."interaction_id",
    checked."customer_id",
    checked."agent_id",
    checked."survey_type",
    checked."send_channel",
    checked."main_score",
    checked."nps_category",
    checked."question_1_text",
    checked."question_1_response",
    checked."question_2_text",
    checked."question_2_response",
    checked."question_3_text",
    checked."question_3_response",
    checked."open_comments",
    checked."comment_sentiment",
    checked."response_time_hours",
    checked."campaign_response_rate",
    checked.year,
    checked.month,
    checked._dq_issues,
    checked._source_key,
    manifest.ingested_at as _ingested_at,
    manifest.run_id as _run_id
from checked
left join manifest on manifest.source_key = checked._source_key
-- a PK delivered twice (late or corrected file): keep the most recent ingestion
qualify row_number() over (partition by checked."survey_id" order by manifest.ingested_at desc nulls last, checked._source_key desc) = 1
