-- Generated by transform/generate_silver.py from data_dictionary.py and seeds/enum_mappings.csv.
-- Edit the generator, not this file.
{{ config(post_hook=export_parquet(partitioned=false)) }}

with raw as (
    select * from {{ bronze('service_agents', partitioned=false) }}
),

manifest as (
    {{ bronze_manifest() }}
),

typed as (
    select
        {{ to_type('raw."agent_id"', 'varchar') }} as "agent_id",
        {{ to_type('raw."employee_code"', 'varchar') }} as "employee_code",
        {{ to_type('raw."first_name"', 'varchar') }} as "first_name",
        {{ to_type('raw."last_name"', 'varchar') }} as "last_name",
        {{ to_type('raw."email"', 'varchar') }} as "email",
        {{ to_type('raw."phone"', 'varchar') }} as "phone",
        {{ to_type('raw."native_accent"', 'varchar') }} as "native_accent",
        {{ to_type('raw."country_of_origin"', 'varchar') }} as "country_of_origin",
        {{ to_type('raw."assigned_branch_id"', 'varchar') }} as "assigned_branch_id",
        {{ to_type('raw."agent_type"', 'varchar') }} as "agent_type",
        {{ to_type('raw."experience_level"', 'varchar') }} as "experience_level",
        {{ to_type('raw."languages"', 'varchar') }} as "languages",
        {{ to_type('raw."specialty"', 'varchar') }} as "specialty",
        {{ to_type('raw."hire_date"', 'date') }} as "hire_date",
        raw."hire_date" as __raw_hire_date,
        {{ to_type('raw."avg_csat"', 'decimal(3,2)') }} as "avg_csat",
        raw."avg_csat" as __raw_avg_csat,
        {{ to_type('raw."total_monthly_interactions"', 'integer') }} as "total_monthly_interactions",
        raw."total_monthly_interactions" as __raw_total_monthly_interactions,
        {{ to_type('raw."agent_status"', 'varchar') }} as "agent_status",
        {{ to_type('raw."work_shift"', 'varchar') }} as "work_shift",
        regexp_extract(raw.filename, 'data/.*$') as _source_key
    from raw as raw
),

checked as (
    select
        *,
        list_filter([
            case when __raw_hire_date is not null and "hire_date" is null then 'cast_failed:hire_date' end,
            case when __raw_avg_csat is not null and "avg_csat" is null then 'cast_failed:avg_csat' end,
            case when __raw_total_monthly_interactions is not null and "total_monthly_interactions" is null then 'cast_failed:total_monthly_interactions' end,
            case when "agent_id" is null then 'not_null:agent_id' end,
            case when "employee_code" is null then 'not_null:employee_code' end,
            case when "first_name" is null then 'not_null:first_name' end,
            case when "last_name" is null then 'not_null:last_name' end,
            case when "email" is null then 'not_null:email' end,
            case when "native_accent" is null then 'not_null:native_accent' end,
            case when "country_of_origin" is null then 'not_null:country_of_origin' end,
            case when "agent_type" is null then 'not_null:agent_type' end,
            case when "experience_level" is null then 'not_null:experience_level' end,
            case when "languages" is null then 'not_null:languages' end,
            case when "hire_date" is null then 'not_null:hire_date' end,
            case when "agent_status" is null then 'not_null:agent_status' end,
            case when "work_shift" is null then 'not_null:work_shift' end,
            case when "native_accent" not in ('mexican', 'colombian', 'argentine') then 'undocumented_value:native_accent' end,
            case when "agent_type" not in ('Phone', 'In-Person', 'Digital', 'Hybrid') then 'undocumented_value:agent_type' end,
            case when "experience_level" not in ('Junior', 'Mid-Senior', 'Senior', 'Specialist') then 'undocumented_value:experience_level' end,
            case when "agent_status" not in ('Active', 'Vacation', 'Leave', 'Inactive') then 'undocumented_value:agent_status' end,
            case when "work_shift" not in ('Morning', 'Afternoon', 'Night', 'Rotating') then 'undocumented_value:work_shift' end,
            case when "avg_csat" not between 1 and 5 then 'out_of_range:avg_csat' end
        ], x -> x is not null) as _dq_issues
    from typed
)

select
    checked."agent_id",
    checked."employee_code",
    checked."first_name",
    checked."last_name",
    checked."email",
    checked."phone",
    checked."native_accent",
    checked."country_of_origin",
    checked."assigned_branch_id",
    checked."agent_type",
    checked."experience_level",
    checked."languages",
    checked."specialty",
    checked."hire_date",
    checked."avg_csat",
    checked."total_monthly_interactions",
    checked."agent_status",
    checked."work_shift",
    checked._dq_issues,
    checked._source_key,
    manifest.ingested_at as _ingested_at,
    manifest.run_id as _run_id
from checked
left join manifest on manifest.source_key = checked._source_key
-- a PK delivered twice (late or corrected file): keep the most recent ingestion
qualify row_number() over (partition by checked."agent_id" order by manifest.ingested_at desc nulls last, checked._source_key desc) = 1
