"""Mock core-banking tools. Every call takes the session, checks permissions, and writes an audit record.

No LangGraph: plain async functions with Pydantic I/O for the future agent orchestrator.
Writes go to InMemoryCasesBackend until Postgres cases.* exists.
"""

from minsky_api.tools.bank import (
    block_card,
    create_handoff,
    evaluate_dispute,
    find_transactions,
    get_dispute,
    get_transaction,
    get_transactions,
    open_dispute,
)
from minsky_api.tools.confirm import classify_reply
from minsky_api.tools.context import ToolContext
from minsky_api.tools.errors import ToolDenied, ToolError
from minsky_api.tools.schemas import (
    BlockCardArgs,
    BlockCardResult,
    CardBlockView,
    ClassifyReplyArgs,
    ClassifyReplyResult,
    CreateHandoffArgs,
    CreateHandoffResult,
    DisputeView,
    EvaluateDisputeArgs,
    EvaluateDisputeResult,
    FindTransactionsArgs,
    FindTransactionsResult,
    FitView,
    GetDisputeArgs,
    GetDisputeResult,
    GetTransactionArgs,
    GetTransactionResult,
    GetTransactionsArgs,
    GetTransactionsResult,
    HandoffView,
    MatchedTransactionView,
    OpenDisputeArgs,
    OpenDisputeResult,
    ProductView,
    TransactionView,
)

__all__ = [
    "BlockCardArgs",
    "BlockCardResult",
    "CardBlockView",
    "ClassifyReplyArgs",
    "ClassifyReplyResult",
    "CreateHandoffArgs",
    "CreateHandoffResult",
    "DisputeView",
    "EvaluateDisputeArgs",
    "EvaluateDisputeResult",
    "FindTransactionsArgs",
    "FindTransactionsResult",
    "FitView",
    "GetDisputeArgs",
    "GetDisputeResult",
    "GetTransactionArgs",
    "GetTransactionResult",
    "GetTransactionsArgs",
    "GetTransactionsResult",
    "HandoffView",
    "MatchedTransactionView",
    "OpenDisputeArgs",
    "OpenDisputeResult",
    "ProductView",
    "ToolContext",
    "ToolDenied",
    "ToolError",
    "TransactionView",
    "block_card",
    "classify_reply",
    "create_handoff",
    "evaluate_dispute",
    "find_transactions",
    "get_dispute",
    "get_transaction",
    "get_transactions",
    "open_dispute",
]
